// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvijTJFDOvkoGM0rSbc7PcceTOxsLmF9Q',
    appId: '1:33604572580:web:944b120fc5bb77f7e29d31',
    messagingSenderId: '33604572580',
    projectId: 'jeleapps-9541b',
    authDomain: 'jeleapps-9541b.firebaseapp.com',
    storageBucket: 'jeleapps-9541b.appspot.com',
    measurementId: 'G-6J5YN09XG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3aKbrsnm5-HmbUU2BZy8MbuIUQtBV1r8',
    appId: '1:33604572580:android:3f1d74df6217b976e29d31',
    messagingSenderId: '33604572580',
    projectId: 'jeleapps-9541b',
    storageBucket: 'jeleapps-9541b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc1MP70tmB86EQVPn_daqnuLuT83778-g',
    appId: '1:33604572580:ios:dd8064e2ef246a75e29d31',
    messagingSenderId: '33604572580',
    projectId: 'jeleapps-9541b',
    storageBucket: 'jeleapps-9541b.appspot.com',
    iosBundleId: 'com.example.jeleApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc1MP70tmB86EQVPn_daqnuLuT83778-g',
    appId: '1:33604572580:ios:dd8064e2ef246a75e29d31',
    messagingSenderId: '33604572580',
    projectId: 'jeleapps-9541b',
    storageBucket: 'jeleapps-9541b.appspot.com',
    iosBundleId: 'com.example.jeleApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvijTJFDOvkoGM0rSbc7PcceTOxsLmF9Q',
    appId: '1:33604572580:web:cd7453ba4eea73a5e29d31',
    messagingSenderId: '33604572580',
    projectId: 'jeleapps-9541b',
    authDomain: 'jeleapps-9541b.firebaseapp.com',
    storageBucket: 'jeleapps-9541b.appspot.com',
    measurementId: 'G-14M4KGXZJ9',
  );
}
